# Makefile para o jogo 4 em linha

CC = gcc
CFLAGS = -Wall -c
LIBS =
OBJS = main.o jogo.o pipes.o

# Alvo por defeito
all: 4emlinha

main.o: main.c 4line.h
	$(CC) $(CFLAGS) -o main.o main.c

jogo.o: jogo.c 4line.h
	$(CC) $(CFLAGS) -o jogo.o jogo.c

pipes.o: pipes.c 4line.h
	$(CC) $(CFLAGS) -o pipes.o pipes.c

4emlinha: $(OBJS)
	$(CC) -o 4emlinha $(OBJS) $(LIBS)

clean:
	rm -f 4emlinha *.o *~
	echo "Removidos ficheiros executáveis, objetos e temporários."